LIQ_SERVER_DB="${HOME}/.liq/server"
LIQ_SERVER_PID_FILE="${LIQ_SERVER_DB}/liq-server.pid"

LIQ_SERVER_STATUS_RUNNING=0
LIQ_SERVER_STATUS_STOPPED=101
LIQ_SERVER_STATUS_STARTING=102
LIQ_SERVER_STATUS_RECOVERABLE=103
LIQ_SERVER_STATUS_UNRECOVERABLE=104
