name: Liquid Labs CI Unit Tests for Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and test package on ${{ matrix.os }}/${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 18.x, 19.x ]
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: TERM=xterm-256color npm run build --if-present
      - run: TERM=xterm-256color npm test